apiVersion: ENC[AES256_GCM,data:MaM=,iv:opChKb+VExtkPKCTWuIn2fsahbonBEZ+YCX9+eFVBx4=,tag:8LlYIlFzwhcMRPEJgygzHQ==,type:str]
kind: ENC[AES256_GCM,data:FBhKhs6e,iv:mvsFxOAn4rCm5Kg0QmGNMclurqZ9CXMPeSX9534mROE=,tag:z3kyPEtfor6Q1YsZWJIc1w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MKrUz3bZqxYdLnHOZWtkqZmCaA==,iv:T93LwoSJwLuadPDeWEJVuZ74CQAzwe3uiq9gZVCVEAw=,tag:AQuwlnpaC3yhLIS7Zcibhw==,type:str]
    namespace: ENC[AES256_GCM,data:3HPim+OWxjZG82fA3g==,iv:CSGOY5Qv5pF0kXUqpGLgHY+JArOwrMpr6TveH+tYUnI=,tag:aL2dXRJOUmytPIzpRDZIoA==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:Mzh3XfWZnA==,iv:/hn2RuG0qNH5vHMS/LxavHd6uivGnDL+C8r1i13EkrI=,tag:n7xjuKLxclfSdMzFc3oErw==,type:str]
type: ENC[AES256_GCM,data:o1TN28dT,iv:iWwlJq/jsO8tdIuqlfiC7dadLKdFrPged+fFrNV0PD4=,tag:+gIQtsvZaIOOf23lW1bdIQ==,type:str]
stringData:
    VLLM_API_BASE: ENC[AES256_GCM,data:rIur1JuRVdT0j9Pm0O3hlxMVseBea9Om,iv:+X1blVcrwwEDK/JcDKinBVpYng/foXOYFejCd2JocyA=,tag:/pDcHSLqgXlnP3nh0iRnnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r5cjptkyd4wn82y5flfte4lm7y67nk2wxqhm7ncg5v23ea6seq9sfyjl0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SDhtMlhDUWRpQ082Lzk3
            aXJJLzE0Nm12azltTE5EczB6VEVHazdLcUJnCnUvUm0wMml0ODh0Q0RaK0lVWjlB
            REIxWDBDSklCUVQ2NWsyMGlWek5QeFkKLS0tIGliUUJUQmhnVG1NQUlPM216c2Nj
            SnhVZTg1OURIdFFzV3puaWc4VDh1UjAKmw22kEx0synYSAtQSDuNLhNqIcGxEFRB
            6Bhen/VGTnF6QBdHoJlaPhU6GrR/UrMWOWdnxGRV4bc4mVimi6w/eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-12T04:22:46Z"
    mac: ENC[AES256_GCM,data:+/OWYP+/dUNIHo1VaQ9Wc0kYyAaCW99k2+GLbnUFmz0p7103teEtKGbZ2vDn2ZoveeOPi7LlVdM+0n+yTC2E0CkFwyEOqkcG8urxmnk+VCwqiwN+4YW3oxPQ9SBXIjx+xoodP8YHO2qHmDdmoU0fLXnQX1Xg904KMdR2a9SCvM0=,iv:sf5Mm7SVcLPpTN71eA6Felu65/vxf9cHm0/r91QcPPo=,tag:imuGGOq/xdbsf+ib7/JHwQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
